@echo off
setlocal

:: This is a reference template.
:: The actual mt-skill.bat is generated by install-mt-skill.bat
:: with the correct repository path for your machine.

set "SKILLS_REPO=D:\Project\skills"

if "%1"=="update" (
    echo Updating skills repository...
    cd /d "%SKILLS_REPO%" && git pull
    if %errorlevel% equ 0 (
        echo Update completed successfully.
    ) else (
        echo Update failed.
    )
    goto :eof
)

echo Installing skills from local repository...
npx skills@latest add "%SKILLS_REPO%"
